### ISSUE TITLE
SSL certificate is expired

### ISSUE THREAD

**Issue by cdlans** [PintaProject/website#14]
Chrome does not load the website.

Expired: Sunday, 29. March 2020 at 00:23:00 Central European Standard Time

**Comment by cameronwhite** [comment]
Thanks for the heads up, I've messaged the original maintainer (Jonathan) who's in charge of the website

**Comment by cameronwhite** [comment]
I'll close this as a duplicate of https://bugs.launchpad.net/pinta/+bug/1869740
