### ISSUE TITLE
Implement RSS feed

### ISSUE THREAD

**Issue by wonea** [PintaProject/website#6]
I have a keen interest in reading about, and keeping up with Pinta. I use Feedly for my RSS feeds, and would love to read about Pinta releases as they happen.

**Comment by versavius** [comment]
Is there any requirement by anyone for this, its just no one has commented or requested this so im guessing this is not a popular request, i think this item should be closed as its not a popular feature.

**Comment by cameronwhite** [comment]
The website has been migrated to be hosted on Github, so I've moved this to https://github.com/PintaProject/pintaproject.github.io/issues/2.
It's probably much easier to implement this now that the website is generated through Jekyll!
